# Generated by Django 3.0.7 on 2020-07-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
    ]
